[project]
name = "adk-demo"
version = "0.1.0"
description = ""
authors = [{ name = "Aaron Davis" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["google-cloud-aiplatform", "google-adk"]
